### PR TITLE
Add sign in

### PR DESCRIPTION
**Pull request by christopeak**
Hey Michelle,

I've spent a bit playing around with foundation.  I like it!  I still don't understand how some of the css files are getting loaded though.  For example I haven't figured out how to change the color of the alert box that pops up when someone has signed in or logged out.  

I did have fun playing around with the colors and whatnot.  I'm not a design expert so if you'd like to mess with the look and feel, go right ahead!  

This PR addresses issues #8 and #9.

### CODE REVIEW

**Comment by michellehyu** [comment]
Nice!! I am glad you like it! I'll take a look later today :)

**Comment by christopeak** [comment]
Also I gave it a placeholder title while I was playing with Foundation. It doesn't have to stick around of course. Just sayin.

On Aug 8, 2015, at 4:19 PM, michellehyu <notifications@github.com<mailto:notifications@github.com>> wrote:

Nice!! I am glad you like it! I'll take a look later today :)

Sent from TypeMail

On Aug 8, 2015, 16:11, at 16:11, christopeak <notifications@github.com<mailto:notifications@github.com>> wrote:

> Hey Michelle,
> 
> I've spent a bit playing around with foundation. I like it! I still
> don't understand how some of the css files are getting loaded though.
> For example I haven't figured out how to change the color of the alert
> box that pops up when someone has signed in or logged out.
> 
> I did have fun playing around with the colors and whatnot. I'm not a
> design expert so if you'd like to mess with the look and feel, go right
> ahead!
> 
> This PR addresses issues #8 and #9.
> You can view, comment on, or merge this pull request online at:
> 
> https://github.com/michellehyu/recipebook/pull/19
> 
> -- Commit Summary --
> - added users controller and filled out #new action
> - login route now allows a user to log in.
> - added specs
> - specs succeeding
> - merge with new master to integrate foundation
> - basic foundation styling
> - added sign_out functionality and an alert box
> 
> -- File Changes --
> 
> A app/assets/javascripts/sessions.coffee (3)
> A app/assets/javascripts/users.coffee (3)
> R app/assets/stylesheets/application.css.scss (17)
> M app/assets/stylesheets/foundation_and_overrides.scss (4)
> A app/assets/stylesheets/sessions.scss (3)
> A app/assets/stylesheets/users.scss (3)
> A app/controllers/sessions_controller.rb (22)
> A app/controllers/users_controller.rb (21)
> A app/helpers/sessions_helper.rb (9)
> A app/helpers/users_helper.rb (2)
> A app/views/layouts/_flasher.html.erb (7)
> A app/views/layouts/_nav.html.erb (15)
> M app/views/layouts/application.html.erb (30)
> A app/views/sessions/create.html.erb (2)
> A app/views/sessions/new.html.erb (19)
> A app/views/users/new.html.erb (31)
> M app/views/welcome/index.html.erb (19)
> M config/routes.rb (11)
> A spec/controllers/sessions_controller_spec.rb (16)
> A spec/controllers/users_controller_spec.rb (12)
> A spec/features/login_spec.rb (17)
> A spec/helpers/sessions_helper_spec.rb (15)
> A spec/helpers/users_helper_spec.rb (15)
> A spec/views/sessions/create.html.erb_spec.rb (5)
> A spec/views/users/new.html.erb_spec.rb (5)
> 
> -- Patch Links --
> 
> https://github.com/michellehyu/recipebook/pull/19.patch
> https://github.com/michellehyu/recipebook/pull/19.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/michellehyu/recipebook/pull/19

—
Reply to this email directly or view it on GitHubhttps://github.com/michellehyu/recipebook/pull/19#issuecomment-129068587.

---

NOTICE OF PUBLIC DISCLOSURE: This e-mail account is public domain. Any correspondence from or to this e-mail account may be a public record. Accordingly, this e-mail, in whole or in part, may be subject to disclosure pursuant to RCW 42.56, regardless of any claim of confidentiality or privilege asserted by an external party.

**Comment by michellehyu** [comment]
I see. I like the changes you made and have just merged. I still like Recipebook better for the name ;)

**Comment by christopeak** [comment]
Yeah I agree on the title. I had just been horsing around with that other title and had actually forgotten to change it back before the PR. At this point I still consider all my content to be temporary anyway. So consider it changed :).

Glad you like the other changes.

On Aug 9, 2015, at 12:40 AM, michellehyu <notifications@github.com<mailto:notifications@github.com>> wrote:

I see. I like the changes you made and have just merged. I still like Recipebook better for the name ;)

—
Reply to this email directly or view it on GitHubhttps://github.com/michellehyu/recipebook/pull/19#issuecomment-129130364.

---

NOTICE OF PUBLIC DISCLOSURE: This e-mail account is public domain. Any correspondence from or to this e-mail account may be a public record. Accordingly, this e-mail, in whole or in part, may be subject to disclosure pursuant to RCW 42.56, regardless of any claim of confidentiality or privilege asserted by an external party.

**Pull request merged**
